### ISSUE TITLE
<mj-include>'s are ignored

### ISSUE THREAD

**Issue by joestrouth1** [attilabuti/vscode-mjml#2] opened 2017-06-19 13:44 UTC
Super grateful for your work on this extension, as it brings better MJML functionality to my favorite editor.

Not sure if this is a feature request or a bug, but .mjml files imported using ```<mj-include>``` do not render in the preview window, nor are they included when exporting to HTML.

Trying to componentize my templates, but swapping out my preheader and header/nav sections with 

```
<mj-include path="./preheader" />
<mj-include path="./header" />

```

results in a preview without either. Exporting to HTML does not include them either, they're just skipped. The linter doesn't recognize mj-include elements. Putting the includes in the same folder or a subfolder, including or omitting the file extension, makes no difference.

This functionality works in the MJML desktop app v2.4.0 running MJML v3.3.3

I am running extension v0.0.2 and VS code 1.13.1 on Windows 10 Creators Update.

**Comment by attilabuti** [comment] 2017-06-21 21:23
Thank you for your contribution!
The issue is fixed on 0.0.4.

**Closed by attilabuti** 2017-06-21 21:23 UTC
