### ISSUE TITLE
when padding applied to mj-section html randers poorly on outlook

### ISSUE THREAD

**Issue by predragbabic** [attilabuti/vscode-mjml#31] opened 2018-06-20 14:52 UTC
Before this version everything worked fine, I went through hoops to install older version (1.2.0) which confirmed newer version was the problem, the same code works fine on official MJML app and via mjml node v4.0.3

**Comment by attilabuti** [comment] 2018-06-22 16:39
Hello @predragbabic

The issue is most likely related to the MJML. "Broken layout in MS Outlook using v4.0.5" [#1201](https://github.com/mjmlio/mjml/issues/1201)

**Comment by attilabuti** [comment] 2018-07-14 16:03
The issue is fixed on 1.4.0.

**Closed by attilabuti** 2018-07-14 16:03 UTC
