### ISSUE TITLE
Preview not showing Images

### ISSUE THREAD

**Issue by tbellAU** [attilabuti/vscode-mjml#41] opened 2018-10-01 13:56 UTC
Hi Attila,

When I use the Preview extension, the images are missing. I can take a screenshot without changing anything and see the images. I can also open the html in my browser and see the images. Is there a setting I need to change?

**Comment by basecde** [comment] 2018-10-01 17:46
I have the same issue, running the current version.

**Comment by attilabuti** [comment] 2018-10-02 17:36
@tbellAU I will fix it in the next update.

**Comment by iskaraltok** [comment] 2018-10-02 19:56
@attilabuti Awesome to hear, I switched computers and thought I broke the install over night. Was having the same issue  👍

**Comment by attilabuti** [comment] 2018-10-03 10:51
The issue is fixed on 1.5.1.

**Closed by attilabuti** 2018-10-03 10:51 UTC
