### ISSUE TITLE
Comment with HTML-style comments?

### ISSUE THREAD

**Issue by michaelroper** [attilabuti/vscode-mjml#40] opened 2018-10-01 06:29 UTC
Hi Attila!

Quick question - when I use the `Command + /` shortcut to comment a line or selection, it is currently only putting `// ` at the start of the line, instead of using HTML comment syntax `<!-- -->`. Is this standard/expected behaviour, or do I possibly have something configured wrong in my VS Code settings?

**Comment by attilabuti** [comment] 2018-10-01 09:04
Hello @michaelroper

Sorry, this is my fault... I will fix it in the next update.

**Comment by michaelroper** [comment] 2018-10-01 09:06
Hah, no worries, thanks! :)

**Comment by attilabuti** [comment] 2018-10-03 10:51
The issue is fixed on 1.5.1.

**Closed by attilabuti** 2018-10-03 10:51 UTC
