### ISSUE TITLE
"mjml.minifyHtmlOutput": true is messing up the rendering of emails

### ISSUE THREAD

**Issue by deviant32** [attilabuti/vscode-mjml#27] opened 2018-05-15 18:59 UTC
when using 
`"mjml.minifyHtmlOutput": true`
it is screwing up the rendering of email in outlook 2000, 2002 and 2003.  I think this issue is actually with MJML, but it might be worth setting the default to false until this is resolved.

**Comment by attilabuti** [comment] 2018-05-17 16:07
Hello @deviant32

The issue is most likely related to the MJML. "Broken layout in MS Outlook using v4.0.5" [#1201](https://github.com/mjmlio/mjml/issues/1201)

**Comment by kmcb777** [comment] 2018-05-17 16:50
@attilabuti yes indeed, thanks for referencing this, this will be fixed in the next mjml release

**Comment by kmcb777** [comment] 2018-06-20 09:37
Hi @deviant32 @attilabuti we released a new beta for mjml 4.1, which you can install with `npm install mjml@next`, could you check if it resolves the problem you had ?

**Comment by nickjl** [comment] 2018-06-20 09:44
Hi, is there an update on when the VS Code package will be updated with the latest MJML release?

**Comment by kmcb777** [comment] 2018-06-20 12:35
@nickjl Hi, mjml 4.1 is currently still in beta. This package will be updated when we release the actual 4.1
I can't tell you when exactly because it still needs some testing but this should be the last beta before the release 🤞

**Comment by nickjl** [comment] 2018-06-20 12:44
Hi @kmcb777 thanks for the update. Great :)

**Comment by attilabuti** [comment] 2018-07-14 16:03
The issue is fixed on 1.4.0.

**Closed by attilabuti** 2018-07-14 16:03 UTC
