### ISSUE TITLE
Supporting component preview/rendering in this extension 

### ISSUE THREAD

**Issue by cbrevik** [attilabuti/vscode-mjml#5] opened 2017-07-06 08:51 UTC
I'm trying to develop some components to use with MJML.

I've tried cloning the following example project: https://github.com/mjmlio/mjml-component-boilerplate

When following the instructions, the custom component will not render in the extension preview, nor is it rendered with the HTML which is generated with this extension. 

It is rendered in the HTML generated by the Gulp-script in that project though. 

Does this extension inspect the `.mjmlconfig` which defines the component? Or is it some other issue?

From VSCode:
![image](https://user-images.githubusercontent.com/4932625/27903433-93d451a8-6239-11e7-99ab-ecd8d703c698.png)

**Comment by attilabuti** [comment] 2017-07-21 16:07
Thank you for your contribution!
The issue is fixed on 0.0.7.

**Closed by attilabuti** 2017-07-21 16:07 UTC

**Comment by jskrzypek** [comment] 2018-05-10 09:36
I think the reason it's broken again is that the .mjmlconfig is not yet working in mjml@^4.0.0 It looks like this PR might be intended to fix that: https://github.com/mjmlio/mjml/pull/1131

**Comment by jskrzypek** [comment] 2018-05-21 14:19
I'll make a new PR to update to the new mjmlconfig functionality that will be released in 4.1.0 (I believe) addition PR to track is here: https://github.com/mjmlio/mjml/pull/1206
