### ISSUE TITLE
Preview not updating when typing

### ISSUE THREAD

**Issue by salinasd** [attilabuti/vscode-mjml#3] opened 2017-06-26 05:17 UTC
Side preview won't update when typing. Using default settings (on the extension package.json file `mjml.updateWhenTyping` is set to `true`).

![jun-26-2017 01-14-14](https://user-images.githubusercontent.com/7526148/27525568-e85426f2-5a0c-11e7-83c0-fdb50692bb3c.gif)

Am I missing something? Great extension, thanks!

Extension version: [0.0.4] (2017-05-21)
OS: macOS 10.12.5
Visual Studio Code 1.13.1

**Comment by attilabuti** [comment] 2017-06-27 20:34
Thank you for your contribution!
I will fix it in the next update.

**Comment by attilabuti** [comment] 2017-06-28 12:18
The issue is fixed on 0.0.5.

**Closed by attilabuti** 2017-06-28 12:18 UTC
