### ISSUE TITLE
Don't beautify mj-style

### ISSUE THREAD

**Issue by nealoke** [attilabuti/vscode-mjml#38] opened 2018-09-19 13:00 UTC
Hi, first of all, great plugin! 👍  The only thing I think were this could improve is when allowing the beautifying is when the `mj-style` is used.

Currently it formats every class and styling on one line which is not handy to work with. The wanted behavior should be like how it beautifies CSS. 

What do you think?

**Comment by KayLeung** [comment] 2018-09-20 10:26
It used `js-beautify` internal. I added `mj-style` to `html.unformatted` option as a temporary solution

**Comment by attilabuti** [comment] 2018-09-28 19:42
The issue is fixed on 1.5.0.

**Closed by attilabuti** 2018-09-28 19:42 UTC
